version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: transcription-db-dev
    restart: unless-stopped
    environment:
      POSTGRES_USER: transcription_user
      POSTGRES_PASSWORD: transcription_pass
      POSTGRES_DB: transcription_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U transcription_user -d transcription_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: transcription-redis-dev
    restart: unless-stopped
    command: redis-server --appendonly yes
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
  redis_data: