version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: transcription-db-dev
    restart: unless-stopped
    environment:
      POSTGRES_USER: transcription_user
      POSTGRES_PASSWORD: transcription_pass
      POSTGRES_DB: transcription_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: transcription-redis-dev
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data: